"""Фикс created_at, используем func.now()

Revision ID: 927600181932
Revises: 7b86e0c4e0dd
Create Date: 2025-02-19 23:29:52.310711

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '927600181932'
down_revision: Union[str, None] = '7b86e0c4e0dd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
